import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'


export default function Home({data_categories}) {
  return (
    <>
      <Head>
        <title>Events </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.nav}>
        <nav>
          <img/>
          <a href='/'>Home</a>
          <a href='event'>Events</a>
          
          <a href='/aboutus'>About us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {data_categories.map((index:any)=>{
          return(<>
          <a href={index.id} style={{background:'white',borderRadius:'10px',margin:'02px',padding:'20px',height:'300px',width:'700px'}}>
            <div>
            <h2>{index.title}</h2>
            <img src={index.image} style={{height:'200px',width:'200px'}}/>
            <p>{index.description}</p>
            </div>
            </a>
          </>);
        })}
       
      </main>
      <footer className={styles.footer}>
        Helllo
      </footer>
    </>
  )
}
import data from '../data/data.json';

export function getServerSideProps(){
    return {
        props:{
            data_categories:data['events_categories']
        }
    }
}